openapi: 3.0.3
info:
  title: Zod Fastify Test Server
  description: API for Zod Fastify Test Server
  version: 0.0.0
components:
  schemas:
    TodoItems:
      type: array
      items:
        $ref: '#/components/schemas/TodoItem'
    TodoItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        label:
          type: string
        dueDate:
          type: string
          format: date-time
        state:
          type: string
          enum:
            - todo
            - in progress
            - done
      required:
        - id
        - label
        - state
      additionalProperties: false
    TodoItemId:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required:
        - id
      additionalProperties: false
paths:
  /item:
    get:
      operationId: getTodoItems
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItems'
    post:
      operationId: postTodoItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItem'
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItems'
  /item/{id}:
    put:
      operationId: putTodoItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItem'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Default Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'

